### ISSUE TITLE
SVG dumping and multi row fluctuations

### ISSUE THREAD

**Issue by techno-yogi** [maddinkunze/handcode#3]
Hi, awesome project! Exciting to try it out. 

I have a couple questions, how to dump SVG intermediate after all the stroke path post processing (ie. left align etc) similar to how the original repo did it. 

Also, I was wondering how to add row amplitude to the lines or apply some path modification for multiple lines. 

imagine human is writing on blank piece of paper, there is always some slant or skew applied to several rows since we cant write straight very well (at least I can't!). 

Any idea what an effective approach would be to add in this type of signal adaptation in the preprocess stage?

**Comment by techno-yogi** [comment]
I realized just uncommenting self._align() would reintroduce these global slant/offsets. 

And probably just need to add back in the svg writer to the _draw function in the HandGCode class

**Comment by maddinkunze** [comment]
Hi, thanks for your kind words.

I completely rewrote how the generated strokes get processed and the documentation is outdated as of version 0.4.0.
Instead of Text -> Neural Network -> SVG -> GCode (-> Postprocessing) my refactored code instead takes the output of the Neural network and samples the strokes directly into a GCode file with all postprocessing steps applied either before converting the stroke coordinates to GCode or directly before writing the commands to the file.

If you just want to preview the GCode, i suggest using a [GCode viewer](https://ncviewer.com/).

If you want to create an SVG instead of GCode using my program, I highly suggest you to look into `src/lib/handwriting/commands.py`
You can create your own set of commands to write an SVG.

Something like 
`page->start: "<svg><path data=\""`
`travel->move: "M {x} {y} "`
`write->move: "L {x} {y} "`
`page->end: "\" /></svg>"`


Regarding custom effects/post-processing:

You can write custom code to add your own post-processing. Please have a look into the file `src/lib/handwriting/gcode.py` in the function `generate(self, settings)`.
You can write your own function (i.e. `def _postprocess(self, settings, passalong)`) and let it run between `self._sample()` and `self._draw()`.
The `passalong` object in particular contains all the sampled strokes for each word. You can modify the strokes to slant/get bigger/... The strokes list should contain (nested) lists of coordinates for each word (split by space character) in the sampled text .

If you dont want to post-process the stroke data this way, you may be able to prime the neural network differently to get slightly different handwriting styles for each word/line. I would suggest looking into `src/lib/handwriting/gcode.py` within `_sample(self, settings, passalong)`. In particular i would look at the `prime` and `biases` variables, but for more information about those please refer to the original project.

Good luck :)

**Comment by maddinkunze** [comment]
Hey, i would like to close this issue within the next few days if you found a solution. If you need any further help you can comment to keep it open or reopen the ticket at a later time. If you need help with any other topics you can always open a new ticket.
